name: JS Actions

on: [push, release]

jobs:
  action:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: hello-action
      uses: ./.github/actions/hello-world
    - name: Extract branch name
      shell: bash
      run: echo |
        ${GITHUB_HEAD_REF}
